In [1]:
import pandas as pd
import numpy as np
import os as os
import altair as alt

I need to import the data.

In [20]:
PATH = '/Users/Carl/Documents/gitfiles/DataVisualizationFinalproj'
temp_data_path = os.path.join(PATH, 'USW00014819.csv')
temp_df = pd.read_csv(temp_data_path)
temp_df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,...,WT06,WT06_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT10,WT10_ATTRIBUTES
0,USW00014819,1997-05-01,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00014819,1997-05-02,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00014819,1997-05-03,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00014819,1997-05-04,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00014819,1997-05-05,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10497,USW00014819,2026-02-03,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10498,USW00014819,2026-02-04,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10499,USW00014819,2026-02-05,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10500,USW00014819,2026-02-06,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",3.0,",,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10501,USW00014819,2026-02-07,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Convert temp to datetime
temp_df['DATE'] = pd.to_datetime(temp_df['DATE'])

# Define function to convert celsius to fahrenheit
def c_to_f(df, col_name, new_col_name=None):
   
    if new_col_name is None:
        new_col_name = col_name + '_F'
        
    df[new_col_name] = ((df[col_name])/10) * 9/5 + 32
    return df

temp_df = c_to_f(temp_df, 'TAVG')

temp_df = c_to_f(temp_df, 'TMAX')

temp_df = c_to_f(temp_df, 'TMIN')

temp_df['max_min_avg'] = (temp_df['TMAX_F'] + temp_df['TMIN_F'])/2

temp_df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,...,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT10,WT10_ATTRIBUTES,TAVG_F,TMAX_F,TMIN_F,max_min_avg
0,USW00014819,1997-05-01,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.08,35.96,48.02
1,USW00014819,1997-05-02,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.06,44.96,49.01
2,USW00014819,1997-05-03,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.02,42.08,49.55
3,USW00014819,1997-05-04,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.04,39.92,51.98
4,USW00014819,1997-05-05,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.02,50.00,62.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10497,USW00014819,2026-02-03,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.02,17.96,23.99
10498,USW00014819,2026-02-04,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.96,17.96,22.46
10499,USW00014819,2026-02-05,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.02,15.98,23.00
10500,USW00014819,2026-02-06,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",3.0,",,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.94,21.92,29.93
10501,USW00014819,2026-02-07,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,1",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.98,12.92,18.95

In [22]:
# Define start and end dates
start_date = "2016-01-01"
end_date = "2022-12-31"

# Subset the dataframe
temp_df = temp_df[(temp_df['DATE'] >= start_date) & (temp_df['DATE'] <= end_date)]
temp_df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,...,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT10,WT10_ATTRIBUTES,TAVG_F,TMAX_F,TMIN_F,max_min_avg
6814,USW00014819,2016-01-01,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.10,20.12,25.61
6815,USW00014819,2016-01-02,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.08,22.10,27.59
6816,USW00014819,2016-01-03,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.10,24.26,27.68
6817,USW00014819,2016-01-04,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.00,25.16,28.58
6818,USW00014819,2016-01-05,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.98,21.20,27.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9365,USW00014819,2022-12-27,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.24,8.24,17.24
9366,USW00014819,2022-12-28,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.96,25.16,35.06
9367,USW00014819,2022-12-29,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.02,44.06,50.54
9368,USW00014819,2022-12-30,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,"T,,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.02,31.10,44.06
9369,USW00014819,2022-12-31,41.78412,-87.75514,185.8,"CHICAGO MIDWAY AIRPORT, IL US",0.0,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.02,27.14,33.08

In [25]:
alt.Chart(temp_df).mark_boxplot().encode(
    alt.X('year(DATE):T', title='Year'), 
    alt.Y('max_min_avg:Q', title='Average Temperature')
)

alt.Chart(...)